---
apiVersion: v1
kind: Namespace
metadata:
  name: spacex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spacex
  name: catalog-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog-app
    spec:
      containers:
      - image: pererakwe/catalog-user:main
        imagePullPolicy: Always
        name: catalog-app
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  namespace: spacex
  name: catalog-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: catalog-app
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spacex
  name: location-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: location-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: location-app
    spec:
      containers:
      - image: pererakwe/location-user:main
        imagePullPolicy: Always
        name: location-app
        ports:
        - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  namespace: spacex
  name: location-service
spec:
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: location-app
  type: LoadBalancer
status:
  loadBalancer: {}
